/*
 * Copyright 2024 LY Corporation
 *
 * LY Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

plugins {
    id 'com.android.application' version '8.12.2'
    id 'org.jetbrains.kotlin.android' version '2.2.10'
    id "com.google.devtools.ksp" version "2.2.10-2.0.2"
    id "org.jlleitschuh.gradle.ktlint" version "13.1.0"
}

// Removed jvmToolchain to use system Java while maintaining Java 11 compatibility

android {
    namespace "jp.co.lycorp.webauthn.sample"
    compileSdkVersion project.compileSdkVersion.toInteger()

    defaultConfig {
        applicationId "jp.co.lycorp.webauthn.sample"
        minSdk project.minSdkVersion.toInteger()
        targetSdk project.targetSdkVersion.toInteger()
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "jp.co.lycorp.webauthn.sample.CustomTestRunner"
    }
    signingConfigs {
        release {
            def keystorePropertiesFile = rootProject.file("keystore.properties")
            if (keystorePropertiesFile.exists()) {
                def keystoreProperties = new Properties()
                keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

                storeFile file(keystoreProperties["storeFile"])
                storePassword keystoreProperties["storePassword"]
                keyAlias keystoreProperties["keyAlias"]
                keyPassword keystoreProperties["keyPassword"]
            } else {
                println("Warning: keystore.properties file not found. Release build will not work.")
            }
        }
        debug {
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = "11"
    }
}

dependencies {
    implementation "androidx.core:core-ktx:$project.coreVersion"
    implementation "androidx.appcompat:appcompat:$project.appcompatVersion"
    implementation "com.google.android.material:material:$project.materialVersion"
    implementation "androidx.constraintlayout:constraintlayout:$project.constraintLayoutVersion"
    implementation "com.google.code.gson:gson:$project.gsonVersion"
    implementation "org.bouncycastle:bcprov-jdk15on:1.67"

    testImplementation "junit:junit:$project.junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$project.testExtJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$project.espressoVersion"

    implementation "com.squareup.retrofit2:retrofit:2.9.0"
    implementation "com.squareup.retrofit2:converter-gson:2.9.0"
    implementation "com.squareup.retrofit2:adapter-rxjava3:2.9.0"
    implementation "com.squareup.okhttp3:logging-interceptor:4.10.0"
    implementation "io.reactivex.rxjava3:rxjava:3.1.5"
    implementation "com.squareup.okhttp3:okhttp-urlconnection:4.10.0"

    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:$project.kotlinxSerializationVersion"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-cbor:$project.kotlinxSerializationVersion"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-core:$project.kotlinxSerializationVersion"
    implementation "androidx.fragment:fragment-ktx:1.6.0"

    // coroutine
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$project.kotlinxCoroutinesVersion"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$project.kotlinxCoroutinesVersion"

    // Room
    implementation "androidx.room:room-runtime:$project.roomVersion"
    ksp "androidx.room:room-compiler:$project.roomVersion"
    implementation "androidx.room:room-ktx:$project.roomVersion"
    androidTestImplementation "androidx.room:room-testing:$project.roomVersion"

    implementation group: "jp.co.lycorp.webauthn", name: "webauthn-kotlin", version: "1.1.0"
}